level5/basicapp/urls.py
from django.conf.urls import re_path
from basicapp import views

#template urls
app_name='basicapp'

urlpatterns=[
    re_path(r'^register/$',views.register,name='register'),
    re_path(r'^user_login/$',views.user_login,name='user_login'),
]

level5/level5/urls.py
from django.contrib import admin
from django.urls import re_path,include
from basicapp import views
urlpatterns = [
    re_path(r'^$',views.index,name="index"),
    re_path('admin/', admin.site.urls),
    re_path(r'^basicapp/',include('basicapp.urls')),
    re_path(r'logout/$',views.user_logout,name='logout'),
    re_path(r'special/',views.special,name='special')
]

level5/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user= models.OneToOneField(User,on_delete=models.CASCADE)

    #additional classes

    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

level5/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')
        

level5/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm,UserProfileInfoForm
#
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,'basicapp/index.html')
@login_required
def special(request):
    return HttpResponse("you have loged in nice")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
def register(request):
    registered=False

    if request.method=="POST":
        user_form= UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()


            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()

            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()
    return render(request,'basicapp/registration.html',{'user_form':user_form,
                                                        'profile_form':profile_form,
                                                        'registered':registered})



def user_login(request):

    if request.method =="POST":
        username=request.POST.get("username")
        password=request.POST.get("password")

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("someone login and tried but failed")
            print("username {} and password{}".format(username,password))
            return HttpResponse("invalid login details")
    else:
        return render(request,'basicapp/login.html',{})

level5/templates/basicapp/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>main</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    </head>
    <body>
        <nav class='navbar navbar-default navbar-static-top'>
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">Django</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'basicapp:register' %}">Register</a></li>
                    {% if user.is_authenticated %}
                    <li><a class='navbar-link' href="{% url 'logout' %}">LOGOUT</a></li>
                    {%else%}
                    <li><a class='navbar-link' href="{% url 'basicapp:user_login' %}">LOGIN</a></li>
                    {% endif %}
                
                
                
                
                
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body_block %}
            {% endblock %} 
        </div>
    </body>
</html>

level5/templates/basicapp/index.html
{%extends "basicapp/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>django level 5</h1>
</div>

{% endblock %}

level5/templates/basicapp/login.html
{% extends 'basicapp/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>please login</h1>
    <form action="{%url 'basicapp:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="enter username">

        <label for="password">Password:</label>
        <input type="password" name="password">
        <input type="submit" name="" value="Login">
    </form>
</div>
{% endblock %}

level5/templates/basicapp/registration.html
{% extends "basicapp/base.html" %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
    {%if registered %}
    <h1>thank you for registering</h1>
    {%else%}
        <h1>register here!</h1>
        <h1>fill out the form</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>
    {%endif%}
</div>
{% endblock %}